### ISSUE TITLE
AR Approvals

### ISSUE THREAD

**Issue by PatricePascual-ACF** [HHS/Head-Start-TTADP#104] opened 2020-10-19 17:25 UTC

**Comment by PatricePascual-ACF** [comment] 2020-10-19 17:29
User story: Approval (and status)
As a TTA manager(s) responsible for reivewing and approving a submitted activity report, I want to 
1) receive notice that the report needs my review; 
2) approve as is; 
3) make my own edits(?); 
4) request revisions; 
5) review the revisions made and mark "Approved".

**Comment by pamlo412** [comment] 2020-10-26 18:00
Closing this issue as a duplicate of #109. I moved the proposed AC above to 109.

**Closed by pamlo412** 2020-10-26 18:00 UTC
Labels: Needs Design, Needs User Research
