### ISSUE TITLE
Filter the grantee options based on region

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#162] opened 2020-11-18 23:34 UTC
**User story:**
As a TTA Specialist completing an Activity Report, I want the list of grantees available to me for selection to be filtered based on the region (or regions) to which I have permissions so that I don't have to search through an excessively long list of grantees.

**Acceptance criteria:**
- [ ] When a user selects the Grantee radio button and clicks in the associated dropdown, the options that display are filtered to show grantees in their region.

**Exclusions:**
- display of grantees pulled from database #163 
- filtering of non-grantee options based on region - not needed
~- type-ahead in grantee dropdown #165~
~- select one or more grantees #166~

**Comment by kryswisnaskas** [comment] 2021-01-12 16:46
This is a duplicate of #154. Closing this issue.

**Comment by kryswisnaskas** [comment] 2021-01-12 16:47
This functionality will be addressed through #154

**Closed by kryswisnaskas** 2021-01-12 16:46 UTC
Labels: 3, AR Activity Summary, In epic 5, V1.0 MVP, enhancement
