### ISSUE TITLE
Print/PDF Display

### ISSUE THREAD

**Issue by marriej** [HHS/Head-Start-TTADP#394] opened 2021-03-16 16:36 UTC
See attachment of observed behavior in Prod in the Chrome browser.
[AR print  SAMPLE PDF.pdf](https://github.com/HHS/Head-Start-TTADP/files/6150711/AR.print.SAMPLE.PDF.pdf)

Bug in Chrome where text gets rendered under the brower’s header/footer
layout stacking when we expect it not to

**Comment by dcloud** [comment] 2021-03-16 21:15
> Bug in Chrome where text gets rendered under the brower’s header/footer

This appears to actually be an issue with Google Chrome itself, as so far I haven't been able to reproduce in Firefox (or Safari). I tried adjusting margins or setting padding, and so far no changes in our code affected this issue. So it's not actually rendering under the header/footer, it's just getting cut off. Adjusting margins just moved the issue further down the page! Adjusting print margins in Chrome's print dialog did appear to trigger a re-render that mitigated the issue.

**Comment by dcloud** [comment] 2021-03-16 21:15
I can open a PR for the layout-stacking bit separately

**Comment by dcloud** [comment] 2021-03-17 14:45
The Google Chrome bug appears regardless of whether the header/footer are turned on: [Review and submit - Activity Report - TTA Smart Hub.pdf](https://github.com/HHS/Head-Start-TTADP/files/6157198/Review.and.submit.-.Activity.Report.-.TTA.Smart.Hub.pdf).

**Comment by dcloud** [comment] 2021-03-17 18:37
I continued to dig in a little further, and tried setting some additional ["paged media"](https://developer.mozilla.org/en-US/docs/Web/CSS/Paged_Media) styles. 

We could set some manual page breaks using something like `break-after: page` but that would only reduce the likelihood of occurrence by breaking up content onto more pages. If an element couldn't fit on one page, like a really long block of text, this issue could still happen.

I also tested out the `orphans` property, which is about showing a minimum number of lines at the bottom of he page, but that had no apparent effect. The ability to have orphans impact fragments on a page appears to be a draft spec, so that use case may not be supported yet. I'm not certain it would in this situation if it did.

Since the text rendering bug appears only in Chrome to my knowledge, I searched for [bugs filed against Chromium](https://bugs.chromium.org/p/chromium/issues/list?q=component%3AInternals%3EPrinting%20text%20split&can=1). [Chromium Issue 986399](https://bugs.chromium.org/p/chromium/issues/detail?id=986399) seems like a close match, but it was closed as with a reference to a [ticket about mixing page sizes](https://bugs.chromium.org/p/chromium/issues/detail?id=8353580).

I may spend a few more minutes messing with specifying page-orientation and sizes, though those are [draft specifications](https://drafts.csswg.org/css-page/#page-orientation-prop) as well.

**Comment by dcloud** [comment] 2021-03-17 18:50
```
@page {
  size: letter portrait;
}
```

Would be cool if that worked, but it does not.

**Comment by dcloud** [comment] 2021-03-22 15:07
I don't think there's anything we can do at this time to mitigate the "Chrome cuts off text" bug, which appears to be an issue Chrome itself rather than our application.

**Closed** 2021-03-22 15:10 UTC
Labels: bug
